### ISSUE TITLE
Does twoway have a method to control NA?

### ISSUE THREAD

**Issue by SeungminHeo** [friendly/twoway#3]
Hi. I was finding nice two way plot package for median polish and I found your package 'twoway'.

I have a question whether this package can control NAs or not.

In base `medpolish`, I can control NAs using parameter `na.rm = TRUE`

Is there any guide for this?

**Comment by rmheiberger** [comment]
thank you for the question.  we are working on adding the na.rm
feature  and will get back to you in a few days.

Rich

**Comment by rmheiberger** [comment]
Thank you for the suggestion.  The devel branch of twoway on github now
honors the na.rm argument.
It has been tested on exactly one example, the one in demo/example-na.r
Please test it on your examples and let us know how it works.

**Comment by SeungminHeo** [comment]
> Thank you for the suggestion. The devel branch of twoway on github now honors the na.rm argument. It has been tested on exactly one example, the one in demo/example-na.r Please test it on your examples and let us know how it works.

Thank you for your kind reponse and It is sorry that I'm late.

I cloned your devel branch, and tested with my example. It work's fine and I think It can be merged in package because this is functionality of medpolish in stat.

I have one problem with twoway package.. but it seems that this is not the problem of yours. 

Thanks you for your honered reponse :)

**Comment by friendly** [comment]
Merged into master via PR #4
